### PR TITLE
Add git into docker image

### PR DESCRIPTION
**Pull request by eneim**
Getting latest git commit SHA or commit time for stag/debug built is a good practice for fast deployment. A good example could be found [here](https://github.com/nickbutcher/plaid/blob/master/app/build.gradle#L20).

This PR add git to this docker image. Please consider/review this @gfx

### CODE REVIEW

**Comment by gfx** [comment]
Why didn't you use `cat .git/refs/heads/$branch`? No git(1) is required to just get the sha1 hash.

**Comment by eneim** [comment]
That is just a sample of using them. We could allow further access though. In my opinion, accessing ./git directly is not a good idea.

**Comment by gfx** [comment]
I don't want to add more binaries in this Dockerfile anymore because this image is already too large.

Moreover, I don't think it is a good idea to use someone else's Dockerfile directly. Just copy a favorite one and use it.  Your Dockerfile is easy to customize, easy to change SDK components.

**Comment by eneim** [comment]
@gfx I agree with the point of using other's dockerfile. I made various reference dockerfiles for Android and use yours as a good reference for the usage with java 8 though. Has been cloning and using this underground for couple weeks (under my own docker hub) before this PR (Because I changed the maintainer name to put my own stuff, but decided that this should belong to the original owner).

For the redundant binaries, I understand your point and would like to close this PR. It totally depends on one's purpose and I would like to keep this dockerfile as simple as possible. Really thanks for this docker.

**Comment by gfx** [comment]
Use your name as the maintainer because you are the maintainer of your Docker files. Adding links to the original Dockerfile in comments is good enough.

:+1:

**Pull request closed without merging**
